"""initial_schema

Revision ID: 0e0205747d8e
Revises: 
Create Date: 2026-04-21 19:29:38.941082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e0205747d8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_leads_created', table_name='leads')
    op.drop_index('idx_leads_niche_id', table_name='leads')
    op.drop_index('idx_leads_source', table_name='leads')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('uq_leads_email', table_name='leads')
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_niche_id'), 'leads', ['niche_id'], unique=False)
    op.drop_index('idx_niches_slug', table_name='niches')
    op.drop_constraint('niches_slug_key', 'niches', type_='unique')
    op.create_index(op.f('ix_niches_slug'), 'niches', ['slug'], unique=True)
    op.drop_index('idx_scores_lead_id', table_name='scores')
    op.create_index(op.f('ix_scores_lead_id'), 'scores', ['lead_id'], unique=False)
    op.drop_constraint('scores_lead_id_fkey', 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key('scores_lead_id_fkey', 'scores', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_scores_lead_id'), table_name='scores')
    op.create_index('idx_scores_lead_id', 'scores', ['lead_id'], unique=False)
    op.drop_index(op.f('ix_niches_slug'), table_name='niches')
    op.create_unique_constraint('niches_slug_key', 'niches', ['slug'])
    op.create_index('idx_niches_slug', 'niches', ['slug'], unique=False)
    op.drop_index(op.f('ix_leads_niche_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.create_index('uq_leads_email', 'leads', [sa.text('lower(email::text)')], unique=True)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_index('idx_leads_source', 'leads', ['source'], unique=False)
    op.create_index('idx_leads_niche_id', 'leads', ['niche_id'], unique=False)
    op.create_index('idx_leads_created', 'leads', [sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
